CREATE TABLE `XT_WxMaterial` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  `media_id` varchar(100) NOT NULL DEFAULT '' COMMENT '素材id',
  `title` varchar(200) NOT NULL DEFAULT '' COMMENT '标题',
  `thumb_media_id` varchar(200) NOT NULL DEFAULT '' COMMENT '封面图片素材id',
  `show_cover_pic` int(1) NOT NULL DEFAULT '0' COMMENT '是否显示封面0不显示1显示',
  `headimgurl` varchar(200) NOT NULL DEFAULT '' COMMENT '素材id',
  `author` varchar(30) NOT NULL DEFAULT '' COMMENT '作者',
  `digest` varchar(500) NOT NULL DEFAULT '' COMMENT '图文消息的摘要',
  `content` text COMMENT '图文消息的具体内容',
  `url` varchar(500) NOT NULL DEFAULT '' COMMENT '图文页的URL',
  `thumb_url` varchar(500) NOT NULL COMMENT '封面url',
  `content_source_url` varchar(500) NOT NULL DEFAULT '' COMMENT '图文消息的原文地址',
  `update_time` datetime DEFAULT NULL COMMENT '图文消息的具体内容',
  `name` varchar(200) NOT NULL DEFAULT '' COMMENT '文件名称',
  `showflag` int(1) NOT NULL DEFAULT '1' COMMENT '是否展示0不展示1展示',
  `menutype` int(2) NOT NULL DEFAULT '1' COMMENT '文章类型1精选干货2工艺下单标准3安装售后保养4常见问题处理5新产品介绍6配套产品详解',
  `type` varchar(10) DEFAULT 'news' COMMENT '素材类型图片（image）视频（video）语音 （voice）图文（news）',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8 COMMENT='图文消息素材列表'